# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c93517591d2f2ef58f46a92904720e67b93b77b7c18925381dfbe100ff64d79ca6604ec7ec864d8a16092e8543355f2a3bee97d60be8206f60cc92932c60daa5

test:
  secret_key_base: 7922920fa9ab34a38fb1d59dff2990d566ca4f3e8799c88b72b286adf75c437b5d0ecfd54eddf30ffd007c14bb99e68d03ff78079eea3c488d13f0c5acb77981

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
